# Generated by Django 3.2.5 on 2021-07-27 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_product_digital'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
