# Generated by Django 3.2.5 on 2021-07-31 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0008_product_hits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='hits',
        ),
    ]
