# Generated by Django 3.2.5 on 2021-08-07 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_category', '0002_alter_category_unique_together'),
        ('ecommerce', '0014_auto_20210807_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce_category.category'),
        ),
    ]
