# Generated by Django 3.2.5 on 2021-08-08 12:52

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0017_alter_product_category'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='product',
            managers=[
                ('featured', django.db.models.manager.Manager()),
            ],
        ),
    ]
