# Generated by Django 3.2.5 on 2021-08-08 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_profile', '0003_profile_is_online'),
        ('ecommerce_comment', '0003_alter_comment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce_profile.profile'),
        ),
    ]
