# Generated by Django 3.2.5 on 2021-07-31 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0009_remove_product_hits'),
        ('user_ip', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IPAddress',
        ),
    ]
