# Generated by Django 3.2.5 on 2021-07-29 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_createduser_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CreatedUser',
        ),
    ]
