# Generated by Django 3.2.5 on 2021-08-06 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_stats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productview',
            name='ip_address',
            field=models.GenericIPAddressField(null=True),
        ),
    ]
