# Generated by Django 3.2.5 on 2021-08-06 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0013_alter_product_favourite'),
        ('ecommerce_stats', '0002_alter_productview_ip_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productview',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.product'),
        ),
    ]
