# Generated by Django 3.2.5 on 2021-07-18 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_cart', '0002_auto_20210718_1251'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
