# Generated by Django 3.2.5 on 2021-07-19 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_cart', '0005_alter_cartproduct_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproduct',
            name='rate',
            field=models.PositiveIntegerField(),
        ),
    ]
