# Generated by Django 3.2.5 on 2021-07-23 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_cart', '0008_alter_order_shipping_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='order',
            name='mobile',
            field=models.CharField(max_length=11, verbose_name='تلفن همراه'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_by',
            field=models.CharField(max_length=200, verbose_name='مرتب سازی بر اساس'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.TextField(max_length=200, verbose_name='آدرس پستی'),
        ),
    ]
