# Generated by Django 3.2.5 on 2021-07-23 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_cart', '0009_auto_20210723_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ordered_by',
        ),
        migrations.AddField(
            model_name='order',
            name='full_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='نام و نام خانوادگی'),
        ),
    ]
