# Generated by Django 3.2.5 on 2021-07-26 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_cart', '0017_alter_cart_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='customer',
            new_name='user',
        ),
    ]
