# Generated by Django 3.2.5 on 2021-08-21 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_cart', '0020_order_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Order Received', 'سفارش دریافت شد'), ('Order Processing', 'درحال پردازش است'), ('On the way', 'در راه است'), ('Order Completed', 'سفارش کامل شد'), ('Order Cancelled', 'سفارش لغو شد')], default=('Order Processing', 'درحال پردازش است'), max_length=50),
        ),
    ]
