# Generated by Django 3.2.5 on 2021-08-05 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchterm',
            name='q',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
